site_name: 我的知识库
site_url: https://chose2008.xyz

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 关于: about.md
# 添加这行，包含 admin 目录为静态文件
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chose2008

# 使用 extra 方式包含 admin 目录
extra_javascript:
  - admin/config.yml
