backend:
  name: github
  repo: chose2008/docs
  branch: main

media_folder: "docs/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "页面"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
